# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: [redacted]

constrain_covariance <- function(X_imp, mask, Sigma_target, lambda, lr, max_iter, tol) {
    .Call(`_lagrange_constrain_covariance`, X_imp, mask, Sigma_target, lambda, lr, max_iter, tol)
}
