# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

constrain_covariance <- function(X_imp, mask, Sigma_target, lambda, lr, max_iter, tol) {
    .Call(`_prism_constrain_covariance`, X_imp, mask, Sigma_target, lambda, lr, max_iter, tol)
}

constrain_covariance_v2 <- function(X_imp, mask, Sigma_target, lambda_sigma, lr, max_iter, tol_kkT, tol_cov, mu_scaled_target = NULL) {
    .Call(`_prism_constrain_covariance_v2`, X_imp, mask, Sigma_target, lambda_sigma, lr, max_iter, tol_kkT, tol_cov, mu_scaled_target)
}

